'use strict';

const config = {
  processingVersion: '2026-07-24-dataset-sensitivity-bev-audit-v0',
  spatialEqualityToleranceM: 0.01,
  offsetSignToleranceM: 0.01,
  maxConsecutiveRouteSGapM: 50,
  maxSpatialJumpM: 12,
  maxLateralOffsetDeltaM: 2,
  minCorrespondenceSlopeAbs: 0.001,
  maxCorrespondenceSlopeAbs: 10,
  maxCorrespondenceSlopeDelta: 0.5,
  slopeQuantizationScale: 1000,
  slopeBinMax: 100000,
  maxLocalHeadingDeltaDeg: 30,
  maxCrossPassHeadingDiffDeg: 10,
  maxAllowedDeviationFromCircularMeanDeg: 15,
  headingTangentQuantizeDeg: 5,
  circularMeanEpsilon: 0.001,
  denseReferenceStepM: 1,
  minCrossPassTrajectoryOverlapM: 5,
  minP3MatchCount: 2,
  maxP3InternalGapM: 1.01,
  minHeadingEvaluationLengthM: 3,
  minHeadingResultant: 1.5,
  lateralToleranceM: 1,
  kPositionSigma: 2,
  kHeadingSigma: 2,
  kPositionHardBound: 3,
  kHeadingHardBound: 3,
  B_partition: 256,
  B_overlap: 64,
  B_heading: 32,
  wGap: 100,
  wLat: 1,
  wSlope: 1,
  wTan: 1,
  bevMaxImageBytes: 1048576,
  bevMaxWidthPx: 4096,
  bevMaxHeightPx: 4096,
  symmetryRelTol: 1e-6,
  eigenRelTol: 1e-8,
  minCorroboratingEvidenceUnits: 2,
  O_max: 8,
  maxOpenPathsPerState: 8,
  maxClosureSubsetsPerState: 256,
  maxBranchesPerPair: 64,
  N_obs: 5809,
  P_cp: 742,
  leaseTtlMs: 30000,
  stagingStaleTtlSeconds: 300,
  lockHeartbeatStaleSeconds: 60,
};

const stage17Gaps = [];

module.exports = { config, stage17Gaps };
